Handle 4xx errors in traversing
spencerwooo/onedrive-vercel-index pull request #231
Opened 2022-01-02 04:38 UTC by myl7

The PR adds code to ignore and skip 4xx errors when traversing. 4xx when traversing is either not setting password or `.password` file not found, which are safe to ignore and skip.

2022-01-02 18:35 UTC, spencerwooo commented
maybe we should have some way of returning an error state that can be used to notify the user about not all files being downloaded - something like

```typescript
let data: any
let error = false
// ... on exception, set error to true before throwing the exception
```

don't know if this is possible as you are using a generator here which in theory should only return a single value...thoughts?

2022-01-03 11:06 UTC, myl7 commented
If error reporting is required, how about adding a new error class to indicate whether the error is fatal, and `try catch` these errors in `for await of`? (or just use the error throwed by axios, but it exposes internal implementation which should be avoided.)

2022-01-24 14:09 UTC, myl7 commented
Demo: https://share.myl.moe/test folder download `test`, which would fail when downloading `/test/test/test` but would not stop downloading but skip it and continue.

2022-01-24 14:41 UTC, spencerwooo requested changes
Other than that question I commented, the rest looks good to me ;)

I'll come back tomorrow for the rest of your PRs, thanks for the help ❤️

2022-01-24 14:41 UTC, spencerwooo commented on components/MultiFileDownloader.tsx
> +                error: [error.status as number, error.message.error as string]
pass this `error` as an Object instead of an array? or is there a specific reason that you are using an array here?

2022-01-25 01:29 UTC, spencerwooo approved these changes
💯

2022-01-25 01:29 UTC, merged