Try to fix CJK search
spencerwooo/onedrive-vercel-index pull request #354
Opened 2022-02-05 15:11 UTC by Ovler-Young

该修改将不再替换搜索词中除数字字母以外的其他字符，将大大改善搜索体验。
另：该api以文件内容搜索，还是较为准确的。

2022-02-05 15:41 UTC, Ovler-Young commented
![Before](https://user-images.githubusercontent.com/44089074/152648408-8f64e4ba-40e9-4075-bb3d-e8eb6215e642.png)
修改前

---
![After](https://user-images.githubusercontent.com/44089074/152648421-3f2a7031-3d80-430e-b9ea-18e2d5392ec1.png)
修改后

2022-02-05 17:13 UTC, myl7 commented
API 跑了几下感觉确实还行？OneDrive API 开窍了？

2022-02-06 02:07 UTC, spencerwooo commented on pages/api/search.ts
> + */
Delete these comments and move them up to the function descriptions

2022-02-06 02:09 UTC, spencerwooo requested changes

2022-02-06 02:09 UTC, spencerwooo commented on pages/api/search.ts
> +  const sanitisedQuery = query
You are still not removing characters including `'`, which causes 400 errors. Take care of this issue.

2022-02-06 02:30 UTC, spencerwooo commented on pages/api/search.ts
> +  const sanitisedQuery = query
FYI: https://github.com/spencerwooo/onedrive-vercel-index/issues/302

2022-02-06 08:03 UTC, spencerwooo approved these changes
🚀

2022-02-06 08:03 UTC, merged